// Generated by Wrangler on Tue Aug 13 2024 01:12:27 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  MICROCMS_SERVICE_DOMAIN: 'p0lxsfmf82'
  MICROCMS_API_KEY: 'ySejhWGkXm5Gvtr3Xh4tJZFHbuZnvDqB3G2b'
  BUN_VERSION: '1.1.22'
}
