// Generated by Wrangler on Mon Aug 12 2024 23:39:33 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  NEWT_SPACE_UID: 'katainaka-no-katada'
  NEWT_CDN_API_TOKEN: 'vLo_uq7-452MZyq7ru0E6rhNz1y2bWL2M5Q4m2cPKZM'
}
